from typing import List, Dict, Any
from langchain_core.documents import Document
from vectorstore.chroma_store import ChromaStore
from utils.logger import get_logger

logger = get_logger(__name__)

class VectorService:
    def __init__(self):
        self.chroma_store = ChromaStore()
        self.db = self.chroma_store.get_db()

    def add_documents(self, documents: List[Document]) -> List[str]:
        """
        Ingests a list of LangChain Document objects into ChromaDB.
        """
        logger.info(f"Ingesting {len(documents)} chunks into ChromaDB")
        # add_documents returns list of IDs generated by Chroma
        ids = self.db.add_documents(documents)
        return ids

    def similarity_search(self, query: str, k: int = 5) -> List[Document]:
        """
        Performs similarity search on the vector store.
        """
        logger.info(f"Performing similarity search for query: '{query}' with k={k}")
        return self.db.similarity_search(query, k=k)

    def delete_document(self, document_id: str) -> bool:
        """
        Deletes all chunks associated with document_id from the vector store.
        """
        logger.info(f"Attempting to delete document chunks with documentId: {document_id}")
        try:
            # Query documents by metadata filter
            results = self.db.get(where={"documentId": document_id})
            ids = results.get("ids", [])
            
            if ids:
                logger.info(f"Found {len(ids)} chunks to delete for documentId {document_id}")
                self.db.delete(ids)
                return True
            else:
                logger.warning(f"No chunks found matching documentId {document_id}")
                return False
        except Exception as e:
            logger.error(f"Error deleting document {document_id}: {str(e)}")
            raise e

    def get_status(self) -> Dict[str, Any]:
        """
        Calculates collection statistics like number of chunks and unique documents.
        """
        try:
            results = self.db.get()
            ids = results.get("ids", [])
            metadatas = results.get("metadatas", []) or []
            
            unique_docs = set()
            for meta in metadatas:
                doc_id = meta.get("documentId")
                if doc_id:
                    unique_docs.add(doc_id)
            
            return {
                "total_chunks": len(ids),
                "unique_documents_count": len(unique_docs),
                "collection_name": self.chroma_store.collection_name,
                "persist_directory": self.chroma_store.persist_directory
            }
        except Exception as e:
            logger.error(f"Failed to get vector store status: {str(e)}")
            return {
                "total_chunks": 0,
                "unique_documents_count": 0,
                "collection_name": self.chroma_store.collection_name,
                "error": str(e)
            }
