import PDFDocument from "pdfkit";
import db from "../configs/db.js";
import { calculateBMI } from "../utils/bmi.js";

export const generateReport = async (req, res) => {
  try {
    const userId = req.user.id;

    const {
      name,
      height,
      weight,
      goal,
      workoutPlan,
      dietPlan,
      waterIntake,
      sleepRecommendation,
      notes,
    } = req.body;

    /* =========================
       BMI CALCULATION
    ========================= */
    const { bmi, category } = calculateBMI(weight, height);

    /* =========================
       SAVE TO DATABASE
    ========================= */

    const [result] = await db.query(
      `INSERT INTO reports
       (user_id, goal, bmi, category, weight, height,
        workout_plan, diet_plan, water_intake,
        sleep_recommendation, notes)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        userId,
        goal,
        bmi,
        category,
        weight,
        height,
        workoutPlan,
        dietPlan,
        waterIntake,
        sleepRecommendation,
        notes,
      ],
    );

    const reportId = result.insertId;

    /* =========================
       PDF GENERATION
    ========================= */

    const doc = new PDFDocument({ margin: 50 });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename=fittrack-report-${reportId}.pdf`,
    );

    doc.pipe(res);

    /* ----- HEADER ----- */

    doc.fontSize(28).fillColor("#10B981").text("FitTrack", { align: "center" });

    doc
      .moveDown(0.3)
      .fontSize(16)
      .fillColor("gray")
      .text("AI Personalized Fitness Assessment Report", {
        align: "center",
      });

    doc.moveDown(1);

    doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor("#10B981").stroke();

    doc.moveDown(1.5);

    /* ----- USER SUMMARY ----- */

    doc
      .fontSize(18)
      .fillColor("black")
      .text("User Summary", { underline: true });

    doc.moveDown(0.5);

    doc
      .fontSize(13)
      .text(`Name: ${name}`)
      .text(`Height: ${height} cm`)
      .text(`Weight: ${weight} kg`)
      .text(`BMI: ${bmi} (${category})`)
      .text(`Report ID: #${reportId}`)
      .text(`Generated On: ${new Date().toLocaleDateString()}`);

    doc.moveDown(1.5);

    /* ----- FITNESS GOAL ----- */

    doc.fontSize(18).text("Fitness Goal", { underline: true });

    doc.moveDown(0.5);
    doc.fontSize(13).text(goal);

    doc.moveDown(1.5);

    /* ----- WORKOUT PLAN ----- */

    doc.fontSize(18).text("Workout Plan", { underline: true });

    doc.moveDown(0.5);
    doc.fontSize(13).text(workoutPlan);

    doc.moveDown(1.5);

    /* ----- DIET PLAN ----- */

    doc.fontSize(18).text("Diet Plan", { underline: true });

    doc.moveDown(0.5);
    doc.fontSize(13).text(dietPlan);

    doc.moveDown(1.5);

    /* ----- DAILY RECOMMENDATIONS ----- */

    doc.fontSize(18).text("Daily Recommendations", { underline: true });

    doc.moveDown(0.5);

    doc
      .fontSize(13)
      .text(`Recommended Water Intake: ${waterIntake}`)
      .text(`Recommended Sleep: ${sleepRecommendation}`);

    doc.moveDown(1.5);

    /* ----- AI NOTES ----- */

    doc.fontSize(18).text("AI Coach Notes", { underline: true });

    doc.moveDown(0.5);
    doc.fontSize(13).text(notes || "Stay consistent and track daily progress.");

    doc.moveDown(2);

    /* ----- FOOTER ----- */

    doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor("#10B981").stroke();

    doc.moveDown(0.7);

    doc
      .fontSize(12)
      .fillColor("gray")
      .text("Generated by FitTrack – Your AI Fitness Companion", {
        align: "center",
      });

    doc.end();
  } catch (error) {
    console.error("Report generation error:", error);
    res.status(500).json({ message: "Failed to generate report" });
  }
};
